export const mockTasks = [
  {
    id: '1',
    title: '見積書の再送依頼',
    assignee: '担当者A',
    status: '未処理',
    due_date: '2026-07-05',
    sender: 'tanaka@example-client.co.jp',
    subject: '見積書の件、再送いただけますでしょうか',
    body_preview:
      'お世話になっております。先日ご依頼した見積書ですが、まだ届いていないようです。お手数ですが再送をお願いできますでしょうか。',
    received_at: '2026-06-30T09:12:00+09:00',
  },
  {
    id: '2',
    title: '契約書の内容確認',
    assignee: '担当者B',
    status: '未処理',
    due_date: '2026-07-10',
    sender: 'sato@partner-corp.jp',
    subject: '契約書ドラフトのご確認をお願いします',
    body_preview:
      '添付の契約書ドラフトについて、内容をご確認の上、ご不明点があればご連絡ください。',
    received_at: '2026-06-30T11:45:00+09:00',
  },
  {
    id: '3',
    title: '納期についての問い合わせ',
    assignee: '担当者C',
    status: '返信済み',
    due_date: '2026-07-03',
    sender: 'suzuki@buyer-inc.com',
    subject: '納期のご確認',
    body_preview: '発注した商品の納期について確認させてください。現在の進捗はいかがでしょうか。',
    received_at: '2026-06-29T14:20:00+09:00',
  },
  {
    id: '4',
    title: '請求書送付のお願い',
    assignee: '担当者A',
    status: '対応中',
    due_date: null,
    sender: 'accounting@example-client.co.jp',
    subject: '請求書のご送付をお願いいたします',
    body_preview: '今月分の請求書をご送付いただけますでしょうか。よろしくお願いいたします。',
    received_at: '2026-06-28T16:03:00+09:00',
  },
  {
    id: '5',
    title: '打ち合わせ日程調整',
    assignee: '担当者B',
    status: '完了',
    due_date: '2026-06-25',
    sender: 'yamada@client-x.jp',
    subject: '来週の打ち合わせについて',
    body_preview: '来週のお打ち合わせについて、候補日をいくつかいただけますでしょうか。',
    received_at: '2026-06-24T10:00:00+09:00',
  },
]
